# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- meow

pool:
  name: 'Meow-hosted'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkDirectory: '/home/david/.sdkman/candidates/java/8.0.472-tem'

    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target'
    artifactName: 'drop'
