---
- name: Copy setup_tables.sql into container
  community.docker.docker_container_copy_into:
    container: "{{ postgres_container }}"
    path: "{{ role_path }}/files/tables.sql"
    container_path: /tmp/tables.sql

- name: Run sql script
  community.docker.docker_container_exec:
    container: "{{ postgres_container }}"
    command: psql -U "{{ postgres_user }}" -d "{{ postgres_db }}" -f /tmp/tables.sql
